{
	"version": 1650408470,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/startbut-sheet0.png",
		"images/select-sheet0.png",
		"images/select-sheet1.png",
		"images/select-sheet2.png",
		"images/rbut-sheet0.png",
		"images/lbut-sheet0.png",
		"images/tiledbackground3.png",
		"images/exit-sheet0.png",
		"images/tank1-sheet0.png",
		"images/tank1-sheet1.png",
		"images/tank1-sheet2.png",
		"images/tank2-sheet0.png",
		"images/tank2-sheet1.png",
		"images/tank2-sheet2.png",
		"images/tank2-sheet3.png",
		"images/back-sheet0.png",
		"images/tiledbackground4.png",
		"images/heart.png",
		"images/alien1-sheet0.png",
		"images/tiledbackground5.png",
		"images/bomb-sheet0.png",
		"images/bomb-sheet1.png",
		"images/bomb-sheet2.png",
		"images/tank3-sheet0.png",
		"images/tank3-sheet1.png",
		"images/particles.png",
		"images/gameover.png",
		"images/restart-sheet0.png",
		"images/sprite-sheet0.png",
		"images/bullet-sheet0.png",
		"images/tiledbackground6.png",
		"images/tiledbackground7.png",
		"images/tiledbackground8.png",
		"images/tiledbackground9.png",
		"images/howto-sheet0.png",
		"images/tiledbackground10.png",
		"media/cannon-shot-14799.m4a",
		"media/cannon-shot-14799.ogg",
		"media/explosion-5.m4a",
		"media/explosion-5.ogg",
		"media/(ingame)war-is-coming-103662 (online-audio-converter.com).m4a",
		"media/(ingame)war-is-coming-103662 (online-audio-converter.com).ogg",
		"media/(menu)bensound-epic (online-audio-converter.com).m4a",
		"media/(menu)bensound-epic (online-audio-converter.com).ogg",
		"media/tankdrivein23.ogg",
		"media/qwertyuio.m4a",
		"media/qwertyuio.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}